### ISSUE TITLE
[修練1] クラスの扱い

### ISSUE THREAD

**Issue by ms2sato** [tomoharutsutsumi/class_practice#1]
# 1. インスタンスを作成して呼び出す
下記のクラスを書いて、`Messanger` のインスタンスをひとつ作り、`show_message` を呼び出してください。

```rb
class Messanger
  def show_message
    puts 'this is test'
  end
end
```

# 2. 新しくクラスを作る1

- 新しいクラス `MyClass` を作成します。
- `MyClass` の `start` メソッドを呼ぶと、`Messanger` のインスタンスから `show_message` を呼ぶようにしてください。
- この時、`MyClass`の`start`メソッド内で `Messanger` のインスタンスを作成するものとします。

# 3. 新しくクラスを作る2

- 新しいクラス `MyClass` を作成します。
- `MyClass` の `start` メソッドを呼ぶと、`Messanger` のインスタンスから `show_message` を呼ぶようにしてください。
- この時、 `MyClass` のコンストラクタで `Messanger` のインスタンスを受け取るものとします。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 
質問です。コメントにも書いているのですが、
initializeメソッドで@messagerにインスタンスを入れたらstartでもそのまま、@messengerにある値を使えるのでしょうか。


def start
initialize
@messanger.show_message
end
みたいにはならないのですか？
以前コミログのindexメソッド内でrankメソッドを呼び出すときは、メソッド内でメソッドを呼び出していたのですが。。。その時みたいにはならないのでしょうか。
これはinitializeメソッドの特性なのでしょうか。それともまた別の理由でしょうか。


何卒よろしくお願いします。

**Comment by ms2sato** [comment]
@tomoharutsutsumi initializeメソッドは、 newをしてインスタンス化した瞬間に呼ばれる特殊なメソッドです。

Messanger.new した瞬間に initialize は呼ばれます。
