### ISSUE TITLE
[修練2] 別のところで動いていたメソッドを移動する。

### ISSUE THREAD

**Issue by ms2sato** [tomoharutsutsumi/class_practice#2]
https://github.com/tomoharutsutsumi/class_practice/commit/b3a7c74ff8d8bd2576a1bfe62075802a9c3179e5

の続きです。

# 1. MyClassのstartメソッドを修正する
start メソッドの前後に文字列出力を入れてください。
以下のような結果になればOKです。

```
--- begin start ---
this is test
--- end start ---
```

# 2. MyClassのstartメソッドを分解する。
`--- begin start ---` という出力をしているところをメソッドにしてください。
同様に`--- end start ---` という出力をしているところをメソッドにしてください。

制限をつけます。
- begin_start、end_start のメソッドは二つともプライベートにしてください。
- 出力される結果は1の時と変わりません（リファクタリングです）。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 追加しました！

**Comment by ms2sato** [comment]
@tomoharutsutsumi 制限を2番に追加したのでこれに従うこと。

**Comment by tomoharutsutsumi** [comment]
@ms2sato startメソッドを呼び出した時のみ、begin_startとend_startが呼び出されるようにするということですよね。やってみました。

**Comment by ms2sato** [comment]
@tomoharutsutsumi OK。結果は大丈夫そう。明日また話しましょう。

**Comment by ms2sato** [comment]
@tomoharutsutsumi ごめん 一点気になった。https://github.com/tomoharutsutsumi/class_practice/commit/b3a7c74ff8d8bd2576a1bfe62075802a9c3179e5#r29376018

これってどうして？
