### ISSUE TITLE
[修練3]クラス内で値をいじる

### ISSUE THREAD

**Issue by ms2sato** [tomoharutsutsumi/class_practice#3]
https://github.com/tomoharutsutsumi/class_practice/issues/2
の続きです。

## `Messanger` クラスに以下の仕様を追加します。

- `show_message` は、 デフォルトでは 「this is test」 を返します。
- `messanger.set_message("これはテストです")` というメソッドを使った後は、
  `show_message` は 「これはテストです」を返すようになります。これによりメッセージを様々な値に変えることができます。
- `messanger.message` というメソッドを使うと、現在のメッセージを取得することができます。

## `MyClass` クラスに以下の仕様を追加します。

- コンストラクタで `Messanger`を外から渡せるようにしてください。

## 結果

```rb
messanger = Messanger.new

myclass = Myclass.new(messanger)
myclass.start # this is test と表示されるはず

messanger.set_message("これはテストです")
myclass.start # これはテストです と表示されるはず

puts messanger.message # これはテストです と表示されるはず

messanger.set_message("こんにちは")
myclass.start # なんと表示されますか？
```

## 考えること
- 上記のプログラムがどのような流れで動きを実現しているのか。

**Comment by tomoharutsutsumi** [comment]
@ms2sato @をなぜつけているか問題はまだありますが、取り急ぎできましたのでpushします。
動きの実現については、@myclassと@messangerの関係がなんなのかがわかりません。
