### ISSUE TITLE
色を混ぜるプログラム

### ISSUE THREAD

**Issue by ms2sato** [tomoharutsutsumi/class_practice#5]
以下のような仕様を満たすクラス `Palette` を作ってください。

- プロパティとして `left_color`、`right_color` を持つ（プロパティは https://www.rubylife.jp/ini/class/index6.html で説明されている attr_accessor で作れます。どんなものかは見てみてください。）
- メソッドとして `mazemaze` を持つ
  - `mazemaze` すると、左右の色が混ざった色がかえります。色は :red、:blue、:yellow です。混ざった色の名前をそれぞれシンボルで返してください。
  - もしも :red、:blue、:yellow 以外が入力されたら StandardError でメッセージを `未対応の色です: [入力された色]` として投げてください。

上記のクラスの動作を確認するコードを用意してください。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 一回pushしました。
プロパティの作成、混ざった色を返す、この二点に関しては動くものをご用意できました。
ですが、最後のstandard errorが詰まっています。
begin rescue raise endを利用しすると思い、
beginの下に、それ以外の色を表すelse、rescueに例外チェック、raiseでエラー文章を出そうと考えました。現状下のようなエラーが発生しています。
ruby_second.rb:82: syntax error, unexpected keyword_rescue
      rescue => e
            ^
ruby_second.rb:85: warning: else without rescue is useless

参考にしたのは以下のURlです。
https://www.sejuku.net/blog/19513#rescue

**Comment by ms2sato** [comment]
@tomoharutsutsumi 
https://github.com/tomoharutsutsumi/class_practice/commit/d86b63f2c6f73a74de94b7f34226062e77e6bf06

コメントしておきました。みてみてください。
