### ISSUE TITLE
[Connector]区切り文字を指定して、文字を連結するプログラム

### ISSUE THREAD

**Issue by ms2sato** [tomoharutsutsumi/class_practice#6]
下記のようなクラスを書きましょう。新しいファイルをつくってやりましょう。

- `名前`: Connector
- `プロパティ`: delim（デリミタの略。区切り文字の意味です）
- `公開メソッド`: push(str)
  - push(str)を呼ぶと、文字列を一つConnectorに格納できます（格納するだけ）
- `公開メソッド`: connect
  - connect を呼ぶと、それまで push した全ての文字列の間に delimで示された文字列を挟んで返します。

例:

```
delim を 「,」 カンマ
push で "鈴木" "佐藤" "田中" と順に呼び
connect すると

鈴木,佐藤,田中
が返ります。
```

**Comment by tomoharutsutsumi** [comment]
@ms2sato 
現状報告と質問です。
上記の課題に対して、思いついた作戦は二つです。

１。Conector クラスにarrayクラスを継承させる

コードはこんな感じです。
class Connector < Array
 attr_accessor :delim
end

connector = Connector.new
connector.push("tanaka")
connector.push("EEEEEEEEEE")

思ったこと：このやり方だと、pushの定義が必要なくなってしまう。
connectした時のやり方が不明。なので一度ボツにしました。

２。文字列連結

class Connector
  attr_accessor :delim
  def initialize
    @str = ""
  end

  def push(str)
    @str << str
  end
end

connector = Connector.new
connector.push("wwwww")
connector.push("EEEEEEEEEE")

思ったこと：結果が"wwwwwEEEEEEEE"と文字列連結になるので、valueを別に扱えない。
なのでこれもボツにしました。

困ったこと：純粋に以下の推察で方向性が間違いないかをお伺いしたいです。あと、文字の定義なのですがConnectorに格納するというのは配列を用意するという手法しか思いつきません。
推察：ここまでやってみて配列しかないかなと考えています。ただ配列には格納するが、動かした時に、配列としてpせず、カンマが抜かれた状態、文字列の羅列として見せる方法がないかを模索しています。

何卒よろしくお願いいたします。

**Comment by ms2sato** [comment]
@tomoharutsutsumi おおお！すっげぇよく考えてる。いいよ。とてもいい。

まず、配列が関わりそうだという推察はバッチリです。ほとんど配列のやっていることですからね。そして、delimをアクセッサにしたのもOKですね。

ヒント: 
1番は惜しいです。継承したい気持ちはわかりますが、配列のようなRubyでもともと用意しているクラスを継承するのはまずないので、一回忘れましょう。

継承せずに、配列をインスタンス変数にしたらどうですか？ 2番では文字列をインスタンス変数にできているのだから、配列をインスタンス変数にもできますよね。

connect した時にやる処理って、何か検索したりしましたか？どんなワード入れてます？

**Comment by tomoharutsutsumi** [comment]
@ms2sato できました！　どうでしょうか！

**Comment by ms2sato** [comment]
@tomoharutsutsumi Good! バッチリです！文字列を出力する時には p ではなくて puts を使っておくと、意図がちゃんとわかっていると感じてもらえますよ（なんでもかんでもpすればというものではないよと）

**Comment by ms2sato** [comment]
次も作っているので取り組んでみてください。
今の内容を変えてしまうのは勿体無いので、新しいファイルを作って良いですよ（その方が参考に過去の内容も見やすいし良いと思います。本来はgitなのでこの使い方はしないけど、今は学習が大事なので）。
