### ISSUE TITLE
[Connector] あえてjoinを使わない

### ISSUE THREAD

**Issue by ms2sato** [tomoharutsutsumi/class_practice#7]
今はjoinでデリミタと連結していますが、これをjoinを使わずにロジックを書きましょう。

**Comment by tomoharutsutsumi** [comment]
@ms2sato 
正直joinが万能すぎて困っています。
方向としては、joinの能力を分割して、少し冗長になるが、joinと同じことができるようにするというものです。
配列を文字列にして、いい感じにsplitとかで切り分けられないかな〜と考えていましたが、配列を文字列にするというのがうまくいかず。。。（こんな感じになります。"[\"suzuki\", \"tanaka\", \"yyyyyy\"]"）
なので、ここから切り分けるのは難しいと考えています。
今からは配列は配列として扱い、なんとかjoinをつかわず区切ることができないか模索しています。

**Comment by ms2sato** [comment]
@tomoharutsutsumi 

> 方向としては、joinの能力を分割して、少し冗長になるが、joinと同じことができるようにするというものです。

この進め方で大丈夫です！


配列に文字列が入っていますよね。一つずつ取り出すことはできますか？中身を 一個ずつ puts するイメージです。そこから考えると良いかもしれません。

**Comment by ms2sato** [comment]
今日はお疲れ様でした！次のIssue立てます！
